-- Os códigos abaixo são templates, é necessário adaptar caso necessário

ALTER TABLE Instancia_Item  [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_Principal_Missao  [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Missao_Sala     [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Item_Loja       [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Loja            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Agente_Penitenciario_Jogador    [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Jogador         [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Agente_Penitenciario            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Prisioneiro     [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Consulta_personagem             [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Item            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Sala            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Inventario      [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Gangue          [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_principal_missao       [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_Principal              [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Missao          [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Dialogo         [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];