-- Os códigos abaixo são templates, é necessário adaptar caso necessário

ALTER TABLE Instancia_Item  [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_Principal_Missao  [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Missao_Sala     [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Item_Loja       [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Loja            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Agente_Penitenciario_Jogador    [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Jogador         [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Agente_Penitenciario            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Prisioneiro     [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Consulta_personagem             [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Item            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Sala            [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Inventario      [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Gangue          [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_principal_missao       [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Objetivo_Principal              [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Missao          [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];
ALTER TABLE Dialogo         [DROP CONSTRAINT | DROP COLUMN] [ADD CONSTRAINT | ADD COLUMN];



-- Adiciona colunas para rastrear compras/vendas
ALTER TABLE Instancia_Item ADD COLUMN preco_compra DECIMAL(10,2);
ALTER TABLE Instancia_Item ADD COLUMN gangue_vendedora VARCHAR(50);

-- Adiciona constraints para o sistema de loja
ALTER TABLE Instancia_Item ADD CONSTRAINT fk_inventario 
FOREIGN KEY (id_inventario) REFERENCES Inventario(id_inventario);

-- Adiciona verificação de preço positivo
ALTER TABLE Loja ADD CONSTRAINT check_preco_positivo 
CHECK (preco > 0);